import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './theme.css';

const company = { name:'鴻亮國際貿易有限公司', address:'UNIT 9, 1/F, THE CLOUD,111 TUNG CHAU STREET,TAI KOK TSUI,HONG KONG', email:'fangchifirm@outlook.com', phone:'Official phone to be supplied', registration:'Official registration number to be supplied' };
const categoryMeta = [
  {name:'Furniture', intro:'Quiet silhouettes, honest materials, lasting comfort.'},
  {name:'Soft Furnishings', intro:'Tactile layers that make a room feel like yours.'},
  {name:'Home Essentials', intro:'Useful everyday pieces, made to earn their place.'},
  {name:'Decor & Lighting', intro:'Small rituals and warm pools of light.'},
  {name:'Kitchen & Bath', intro:'Practical finishes for the rooms that work hardest.'}
];
const names = [
  ['Cove Modular Sofa','Ash Platform Bed','Ledge Open Wardrobe','Arc Dining Table','Lowline Coffee Table','Frame Media Console','Noma Drawer Chest','Sora Sideboard','Grid Open Bookcase','Atelier Writing Desk'],
  ['Loom Linen Curtain','Field Flatweave Rug','Knot Textured Cushion','Quiet Abstract Wall Art','Moss Artificial Plant','Cloud Sheer Curtain','Linewood Blind','Tactile Wallcovering','Handloom Tapestry','Nest Seat Cushion'],
  ['Washed Cotton Bedding','Foldaway Storage Box','Rinse Washable Mat','Cloudweight Quilt','Rest Support Pillow','Softline Fitted Sheet','Daily Bath Towel','Wrap Cotton Bathrobe','Weave Laundry Basket','Stack Fabric Bin'],
  ['Cedar Reed Diffuser','Halo Table Lamp','Arc Floor Lamp','Line Wall Sconce','Loom Wall Baskets','Arc Metal Bookends','Ember Table Runner','Fold Woven Screen','Dawn Pendant Lamp','Hearth Metal Lantern'],
  ['Linen Table Mat','Washed Tablecloth','Silicone Heat Mat','Rail Kitchen Rack','Calm Shower Curtain','Grip Bath Mat','Loop Towel Rail','Niche Bath Shelf','Bamboo Counter Organizer','Canvas Laundry Hamper']
];
const prices = [[189,329,159,249,119,229,199,279,179,149],[69,129,39,89,59,65,99,79,119,49],[89,39,29,69,35,32,28,59,49,34],[24,79,149,99,45,35,89,129,119,69],[29,59,39,69,49,45,55,49,39,59]];
const products = categoryMeta.flatMap((cat, ci) => names[ci].map((name, i) => ({id:`${ci}-${i}`, category:cat.name, name, price:prices[ci][i], image:ci===3&&i>=4&&i<=6?`/products/decor-replacement-${String(i-3).padStart(2,'0')}.webp`:`/products/catalog-${String(ci*10+i+1).padStart(2,'0')}.webp`, note: ['Natural texture','Made for daily use','Thoughtful proportions'][i%3]})));

function Icon({children}) { return <span className="icon" aria-hidden="true">{children}</span> }
function Header({cartCount,onCart, onCategory}) { return <header className="site-header"><a className="wordmark" href="#top"><span>F</span> FANGCHI <em>HOME</em></a><nav>{categoryMeta.slice(0,4).map(c=><button key={c.name} onClick={()=>onCategory(c.name)}>{c.name}</button>)}<button onClick={()=>onCategory('All pieces')}>SHOP ALL</button></nav><button className="cart-button" onClick={onCart}><Icon>□</Icon> BAG <b>{cartCount}</b></button></header> }
function Hero({onExplore}) { return <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">A HOME, IN PROGRESS / 2026</p><h1>Objects with<br/><i>room to breathe.</i></h1><p className="hero-text">A considered collection for slower mornings, shared dinners and the everyday beauty of a well-lived home.</p><button className="button button-dark" onClick={onExplore}>EXPLORE THE COLLECTION <span>↘</span></button></div><div className="hero-art"><div className="art-card art-one"></div><div className="art-card art-two"></div><p>FORM / FUNCTION / FEELING</p></div></section> }
function ProductCard({p,onAdd,onBuy}) { return <article className="product-card"><div className="product-image"><img src={p.image} alt={p.name}/><span className="product-note">{p.note}</span></div><div className="product-info"><div><p className="category-label">{p.category}</p><h3>{p.name}</h3></div><strong>${p.price}</strong></div><div className="product-actions"><button onClick={()=>onAdd(p)}>ADD TO CART</button><button onClick={()=>onBuy(p)}>BUY NOW — ${p.price}</button></div></article> }
function Catalog({filter,onFilter,onAdd,onBuy}) { const shown=filter==='All pieces'?products:products.filter(p=>p.category===filter); return <section className="catalog" id="catalog"><div className="section-head"><div><p className="eyebrow">THE COLLECTION</p><h2>Made for <i>living.</i></h2></div><p className="intro">Five edit-led chapters for a home that feels personal, practical and quietly distinct.</p></div><div className="filters">{['All pieces',...categoryMeta.map(c=>c.name)].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>onFilter(f)}>{f}</button>)}</div><div className="product-grid">{shown.map(p=><ProductCard key={p.id} p={p} onAdd={onAdd} onBuy={onBuy}/>)}</div></section> }
function Cart({items,open,onClose,onCheckout,onRemove}) { const total=items.reduce((s,p)=>s+p.price,0); return <><div className={`scrim ${open?'show':''}`} onClick={onClose}></div><aside className={`cart-drawer ${open?'open':''}`}><div className="drawer-head"><div><p className="eyebrow">YOUR BAG</p><h2>{items.length} pieces</h2></div><button onClick={onClose}>×</button></div>{items.length?<><div className="cart-items">{items.map((p,i)=><div className="cart-item" key={`${p.id}-${i}`}><img src={p.image} alt=""/><div><h3>{p.name}</h3><p>${p.price}</p><button onClick={()=>onRemove(i)}>Remove</button></div></div>)}</div><div className="cart-total"><span>Subtotal</span><b>${total}</b></div><button className="button button-dark full" onClick={onCheckout}>CHECKOUT <span>↗</span></button></>:<p className="empty">Your bag is ready for something considered.</p>}</aside></> }
function Checkout({items,onBack}) { const [method,setMethod]=useState('PayPal'); const [done,setDone]=useState(false); const total=items.reduce((s,p)=>s+p.price,0); return <main className="checkout-page"><button className="back" onClick={onBack}>← Back to collection</button><div className="checkout-layout"><div><p className="eyebrow">SECURE CHECKOUT</p><h1>Almost <i>home.</i></h1><div className="checkout-block"><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Shipping address<input placeholder="Street, city, postal code"/></label><div className="two"><label>Country<input placeholder="Country"/></label><label>Phone<input placeholder="Phone number"/></label></div></div><div className="checkout-block"><h3>Payment method</h3><div className="pay-options">{['PayPal','Visa','Credit Card'].map(x=><button className={method===x?'selected':''} onClick={()=>setMethod(x)} key={x}><span className={`pay-logo ${x.replace(' ','').toLowerCase()}`}>{x==='Credit Card'?'▣':x}</span>{x}<span>○</span></button>)}</div><p className="demo-note">Demo checkout: connect your merchant provider to process live payments.</p></div>{done?<div className="success">Thank you — your demo order has been received.</div>:<button className="button button-dark" onClick={()=>setDone(true)}>PLACE DEMO ORDER — ${total} <span>↗</span></button>}</div><div className="order-summary"><p className="eyebrow">ORDER SUMMARY</p>{items.map((p,i)=><div className="summary-line" key={`${p.id}-${i}`}><span>{p.name}</span><b>${p.price}</b></div>)}<hr/><div className="summary-line"><span>Total</span><b>${total}</b></div></div></div></main> }
const policyContent={
  'About us':['Fangchi Home is a considered home-living collection curated by 鴻亮國際貿易有限公司. We look for useful forms, tactile materials and pieces that become more personal with time.'],
  'Shipping policy':['Orders are prepared within 2–4 business days. Delivery timing and cost are shown at checkout based on destination and parcel size. Oversized furniture may require a scheduled carrier appointment.'],
  'Returns & refunds':['Request a return within 14 days of delivery. Items must be unused, clean and in original protective packaging. Approved refunds are issued to the original payment method after inspection; outbound shipping is non-refundable unless the item arrived damaged.'],
  'Cancellation policy':['You may request cancellation before dispatch by contacting us with your order number. Once a shipment has been collected, the returns process applies.'],
  'Order tracking':['When an order ships, we send a tracking link to the email address supplied at checkout. If tracking has not updated for five business days, contact our support team.'],
  'Privacy policy':['We use order and contact information only to provide service, fulfill orders, prevent fraud and communicate relevant updates. We do not sell personal information. You may request access or correction by email.'],
  'DMCA':['If you believe content on this demo storefront infringes your copyright, send a notice identifying the work, the material, your contact details and a good-faith statement through the official contact channel once supplied by the company.'],
};
function LegalPage({title,onBack}) { const terms=title==='Terms of Service'; return <main className="legal-page"><button className="back" onClick={onBack}>← Back to home</button><p className="eyebrow">FANGCHI HOME / INFORMATION</p><h1>{title}</h1>{terms?<>{['Agreement','Eligibility','Product information','Prices and taxes','Orders','Payment','Delivery','Risk and title','Returns','Refunds','Cancellations','Personal information','Intellectual property','User content','Third-party services','Limitation of liability','Governing law'].map((x,i)=><section key={x}><h2>{i+1}. {x}</h2><p>These Terms describe how Fangchi Home provides its online collection. By using the site or placing an order, you agree to use the service lawfully and to the terms in this section. Specific details shown at checkout and in our policies form part of the agreement.</p></section>)}</>:<div className="legal-copy">{policyContent[title]?.map(p=><p key={p}>{p}</p>)}</div>}</main> }
function Footer({onPage}) { return <footer><div className="footer-top"><div><a className="wordmark" href="#top"><span>F</span> FANGCHI <em>HOME</em></a><p>Objects with room to breathe.<br/>A quieter way to live with things.</p><a className="footer-email" href={`mailto:${company.email}`}>{company.email} <span>↗</span></a></div><div className="footer-col"><h4>SHOP</h4>{categoryMeta.map(c=><button key={c.name} onClick={()=>onPage('collection')}>{c.name}</button>)}</div><div className="footer-col"><h4>HELP</h4>{['Shipping policy','Order tracking','Returns & refunds','Cancellation policy'].map(x=><button key={x} onClick={()=>onPage(x)}>{x}</button>)}</div><div className="footer-col"><h4>COMPANY</h4>{['About us','Terms of Service','Privacy policy','DMCA'].map(x=><button key={x} onClick={()=>onPage(x)}>{x}</button>)}</div></div><div className="company-strip"><span>{company.name}</span><span>{company.address}</span><span>{company.email} · {company.phone}</span><span>© 2026 Fangchi Home</span></div></footer> }
function Admin(){const [logged,setLogged]=useState(false);return <main className="admin-page"><div className="admin-card"><p className="eyebrow">FANGCHI HOME / DEMO ADMIN</p><h1>{logged?'Good morning, admin.':'Back office access.'}</h1>{logged?<><p>Catalog, orders and customer service tools are ready for integration.</p><div className="admin-stats"><b>50<br/><small>Products</small></b><b>—<br/><small>Orders today</small></b><b>5<br/><small>Collections</small></b></div><button className="back" onClick={()=>setLogged(false)}>Sign out</button></>:<><label>Email<input defaultValue="admin@fangchihome.com"/></label><label>Password<input type="password" defaultValue="fangchi-demo"/></label><p className="demo-note">Demo-only frontend access. Replace with server-side authentication before production.</p><button className="button button-dark full" onClick={()=>setLogged(true)}>SIGN IN <span>↗</span></button></>}</div></main>}
function App(){const [filter,setFilter]=useState('All pieces');const [items,setItems]=useState([]);const [cartOpen,setCartOpen]=useState(false);const [page,setPage]=useState(window.location.hash==='#/admin'?'admin':'home'); const add=p=>{setItems(x=>[...x,p]);setCartOpen(true)};const buy=p=>{setItems(x=>[...x,p]);setPage('checkout');window.scrollTo(0,0)};const navPage=x=>{if(x==='collection'){setPage('home');setFilter('All pieces');setTimeout(()=>document.querySelector('.catalog')?.scrollIntoView(),0)}else{setPage(x);window.scrollTo(0,0)}}; if(page==='admin')return <Admin/>;if(page==='checkout')return <Checkout items={items} onBack={()=>setPage('home')}/>;if(page!=='home'&&policyContent[page]||page==='Terms of Service')return <LegalPage title={page} onBack={()=>setPage('home')}/>;return <><Header cartCount={items.length} onCart={()=>setCartOpen(true)} onCategory={x=>{setFilter(x);setTimeout(()=>document.querySelector('.catalog')?.scrollIntoView({behavior:'smooth'}),0)}}/><Hero onExplore={()=>document.querySelector('.catalog')?.scrollIntoView({behavior:'smooth'})}/><Catalog filter={filter} onFilter={setFilter} onAdd={add} onBuy={buy}/><div className="manifesto"><p className="eyebrow">OUR POINT OF VIEW</p><h2>Keep what earns<br/><i>its place.</i></h2><p>We believe a home is built slowly: one useful object, one good material, one daily ritual at a time.</p></div><Footer onPage={navPage}/><Cart items={items} open={cartOpen} onClose={()=>setCartOpen(false)} onCheckout={()=>{setCartOpen(false);setPage('checkout');window.scrollTo(0,0)}} onRemove={i=>setItems(x=>x.filter((_,j)=>j!==i))}/></>}
createRoot(document.getElementById('root')).render(<App/>);
